import {parseQuery,resolveEvent,getGuides,keyOf,sourceLink} from './core.js';
const icons={search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',star:'<path d="m12 3 2.8 5.7 6.3.9-4.6 4.5 1.1 6.3-5.6-3-5.6 3 1.1-6.3L3 9.6l6.3-.9Z"/>',book:'<path d="M12 5C8 2 3 3 3 3v16s5-1 9 2c4-3 9-2 9-2V3s-5-1-9 2Zm0 0v16"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v1"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',chevron:'<path d="m6 9 6 6 6-6"/>',back:'<path d="m14 5-7 7 7 7"/>',warning:'<path d="m12 3 10 18H2Z"/><path d="M12 9v5m0 3v1"/>',file:'<path d="M14 3H5v18h14V8Zm0 0v5h5M8 12h8m-8 4h6"/>',wrench:'<path d="M14 7a6 6 0 0 0-7 7l-5 5 3 3 5-5a6 6 0 0 0 7-7l-4 4-3-3 4-4Z"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',open:'<path d="M14 3h7v7m-8 1 8-8M10 3H3v18h18v-7"/>',check:'<path d="m5 12 4 4L19 6"/>'};
function icon(n){return `<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[n]||icons.info}</svg>`;}
const escape=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const app=document.querySelector('#app');let dataset=null;let tab='consulta',currentQuery=null,result=null,showMobile=false,installPrompt=null;
const read=(key)=>{try{const value=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(value)?value.filter(q=>q&&/^\d{3}$/.test(q.code)&&(!q.sub||/^\d{2}$/.test(q.sub))):[];}catch{return [];}};let favorites=read('sacc-930e4-favorites'),history=read('sacc-930e4-history');
function persist(){try{localStorage.setItem('sacc-930e4-favorites',JSON.stringify(favorites));localStorage.setItem('sacc-930e4-history',JSON.stringify(history));}catch{toast('No se pudo guardar en este dispositivo.');}}
function toast(text){const t=document.querySelector('#toast');t.textContent=text;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2500);}
const signature='<span class="signature">SACC</span>';
function updateNav(){document.querySelectorAll('[data-tab]').forEach(b=>{const t=b.dataset.tab;b.innerHTML=icon(t==='consulta'?'search':t==='favoritos'?'star':'book')+`<span>${t==='consulta'?'Consulta':t==='favoritos'?'Favoritos':'Manuales'}</span>`;b.classList.toggle('active',t===tab);b.setAttribute('aria-current',t===tab?'page':'false');});}
function quickButton(q,label){return `<button class="quick-code" data-query="${escape(keyOf(q))}"><strong>${escape(keyOf(q))}</strong><span>${escape(label)}</span></button>`;}
function renderSearch(){const recent=history.slice(0,4);const quick=recent.length?recent.map(q=>quickButton(q,resolveEvent(dataset.events,q)?.event.title||'Consulta guardada')).join(''):['002','025','036','104'].map(c=>quickButton({code:c,sub:null},dataset.events.find(e=>e.code===c).title)).join('');return `<section class="search-panel"><span class="eyebrow">DIAGNÓSTICO · 930E-4</span><h1>Consulta de fallas</h1><p class="intro">Busca por código y subíndice</p><form id="search-form" novalidate><div class="field"><label for="code">Código</label><input id="code" name="code" inputmode="text" autocomplete="off" placeholder="Ej. 36 o 36/4" value="${escape(currentQuery?.code||'')}" aria-describedby="search-hint" maxlength="12"></div><div class="suggestions" id="suggestions"></div><div class="field"><label for="sub">Subíndice</label><input id="sub" name="sub" inputmode="numeric" autocomplete="off" placeholder="Opcional" value="${escape(currentQuery?.sub||'')}" maxlength="2" list="sub-options"><datalist id="sub-options"></datalist></div><p id="search-hint" class="hint">${icon('info')}<span>También puedes escribir <strong>36/4</strong>.</span></p><button class="primary" type="submit">${icon('search')}Consultar</button><p class="error-message" id="search-error" role="alert"></p></form><div class="quick"><div class="section-label">${icon(recent.length?'clock':'file')}${recent.length?'Búsquedas recientes':'Consulta rápida'}</div><div class="quick-grid">${quick}</div></div>${signature}</section>`;}
function restrictedText(restriction){const r=restriction.toUpperCase();if(r==='SIN ENERGIA'||r==='SIN ENERGÍA')return 'Retardo y propulsión no permitidos. Barra link sin energía.';if(r.includes('PROPULSION')||r.includes('PROPULSIÓN'))return 'Propulsión no permitida. Consulta las condiciones del evento en el manual.';if(r.includes('10 MPH'))return 'Límite indicado: 10 mph. Consulta las condiciones del evento en el manual.';if(r.includes('EVENTO')||r.toLowerCase()==='ninguna'||r.toLowerCase()==='ninguno')return 'Restricción registrada en la documentación del evento.';return 'Consulta las condiciones del evento en el manual.';}
function renderResult(){if(!result)return `<section class="result"><div class="empty">${icon('search')}<h2>Encuentra la guía de tu falla</h2><p>Ingresa el código que aparece en la pantalla de diagnóstico.</p></div></section>`;
 const e=result.event,q=currentQuery,sub=q.sub?e.steps.find(s=>s.number===Number(q.sub)):null,known=!q.sub||!!sub,guides=getGuides(e,q.sub);const saved=favorites.some(x=>keyOf(x)===keyOf(q));
 const info=q.sub&&!known?`<div class="notice"><strong>Subíndice ${Number(q.sub)} no disponible para este código.</strong><br>Se muestran todos los subíndices del código ${escape(q.code)}.</div>`:sub?`<p class="selection-note">Subíndice ${Number(q.sub)} resaltado · Todos los detalles disponibles</p>`:'';
 const steps=guides.steps.map((s,i)=>`<article class="step ${s.selected?'selected-step':''}" ${s.selected?'aria-current="true"':''}><span class="step-number ${s.number==null?'plain':''}">${s.number??icon('file')}</span><div class="step-content">${s.number!=null?`<div class="step-heading">Subíndice ${s.number}${s.selected?'<span class="selected-badge">Seleccionado</span>':''}</div>`:''}<p>${escape(s.text)}</p></div></article>`).join('');
 const referenced=[...new Set(guides.steps.flatMap(s=>[...s.text.matchAll(/(?:Eventos?|falla)\s+(\d{1,3})(?:\s+y\s+(\d{1,3}))?/gi)].flatMap(m=>[m[1],m[2]].filter(Boolean))).map(c=>c.padStart(3,'0')))].filter(c=>dataset.events.some(x=>x.code===c)&&c!==e.code);
 const source=dataset.documents.find(x=>x.id==='diagnostico');
 return `<section class="result"><button class="back-mobile" id="back">${icon('back')}Volver a la búsqueda</button><div class="result-head"><div class="result-topline"><span class="eyebrow">${sub?'CÓDIGO Y SUBÍNDICE':'CÓDIGO GENERAL'}</span><button class="favorite ${saved?'selected':''}" id="favorite" aria-label="${saved?'Quitar de favoritos':'Guardar en favoritos'}" aria-pressed="${saved}">${icon('star')}</button></div><div class="code-title">${escape(keyOf(q))}</div><div class="event-title">${escape(e.title)}</div><span class="type-badge">${result.alias?'Inversor 2 · Familia '+e.baseCode:Number(e.code)>=100&&Number(e.code)<200?'Inversor 1':Number(e.code)>=600?'Panel TCI':'Panel PSC'}</span></div><div class="result-body"><p class="guide-label">${q.sub?'Guía completa · Subíndice seleccionado':'Guía general del código'}</p>${info}<div class="restriction">${icon('warning')}<div><strong>${escape(e.restriction||'Sin restricción indicada')}</strong><p>${escape(restrictedText(e.restriction||''))}</p></div></div><details class="accordion"><summary><span class="label">${icon('file')}Condición de detección</span><span class="chevron">${icon('chevron')}</span></summary><div class="detection">${escape(e.detection)}</div></details><details class="accordion" open><summary><span class="label">${icon('wrench')}Guía de diagnóstico</span><span class="chevron">${icon('chevron')}</span></summary>${guides.context?`<div class="detection">${escape(guides.context)}</div>`:''}<div class="steps">${steps||'<div class="detection">No se indica una guía de diagnóstico para este evento.</div>'}</div></details>${referenced.length?`<div class="related">${referenced.map(c=>`<button data-query="${c}">Consultar código ${c}</button>`).join('')}</div>`:''}<div class="source-row"><a class="outlined" href="${sourceLink(source,e.sourcePage)}" target="_blank" rel="noopener">${icon('book')}${e.sourcePage?'Ver página del manual':'Ver documento de diagnóstico'}</a><div class="source-caption"><span>Fuente: diagnóstico de fallas${e.sourcePage?' · Página PDF '+e.sourcePage:''}</span><span>930E-4</span></div></div>${signature}</div></section>`;}
function renderCollection(){return `<section class="page"><div class="page-header"><div><span class="eyebrow">EN ESTE DISPOSITIVO</span><h1>Favoritos</h1></div><span class="count">${favorites.length} guardados</span></div>${favorites.length?`<div class="collection">${favorites.map(q=>{const e=resolveEvent(dataset.events,q)?.event;return `<article class="saved-card"><button class="saved-main" data-query="${escape(keyOf(q))}"><strong>${escape(keyOf(q))}</strong><span>${escape(e?.title||'Código no disponible')}</span><small>Komatsu 930E-4</small></button><button class="remove" data-remove="${escape(keyOf(q))}" aria-label="Quitar ${escape(keyOf(q))} de favoritos">${icon('close')}</button></article>`;}).join('')}</div>`:`<div class="empty">${icon('star')}<h2>Tus guías a mano</h2><p>Toca la estrella de un resultado para guardarlo aquí.</p><button class="primary" data-tab="consulta">Consultar una falla</button></div>`}${signature}</section>`;}
function renderDocuments(){return `<section class="page"><div class="page-header"><div><span class="eyebrow">DOCUMENTACIÓN · 930E-4</span><h1>Manuales y pautas</h1></div><span class="count">${dataset.documents.length} documentos</span></div><div class="doc-grid">${dataset.documents.map(d=>`<article class="doc-card"><div class="doc-icon">${icon(d.id.startsWith('pm')?'wrench':'book')}</div><h2>${escape(d.title)}</h2><p>${escape(d.scope)}</p>${d.parts.map((p,i)=>`<a class="part-link" href="${p.file}" target="_blank" rel="noopener"><span>${d.parts.length>1?`Parte ${i+1} · Páginas ${p.start}–${p.end}`:'Abrir documento'}</span>${icon('open')}</a>`).join('')}<span class="doc-meta">${d.pages} páginas · ${d.parts.reduce((a,p)=>a+p.sizeMb,0).toFixed(1)} MB</span></article>`).join('')}</div>${signature}</section>`;}
function bind(){document.querySelectorAll('[data-query]').forEach(b=>b.onclick=()=>lookup(b.dataset.query));document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;showMobile=false;render();window.scrollTo({top:0});});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{favorites=favorites.filter(q=>keyOf(q)!==b.dataset.remove);persist();render();});const form=document.querySelector('#search-form');if(form){form.onsubmit=e=>{e.preventDefault();lookup(document.querySelector('#code').value,document.querySelector('#sub').value);};document.querySelector('#code').oninput=updateSuggestions;document.querySelector('#sub').oninput=()=>document.querySelector('#search-error').textContent='';updateOptions();}const star=document.querySelector('#favorite');if(star)star.onclick=()=>{const key=keyOf(currentQuery);const exists=favorites.some(q=>keyOf(q)===key);favorites=exists?favorites.filter(q=>keyOf(q)!==key):[{...currentQuery},...favorites];persist();render();toast(exists?'Eliminado de favoritos':'Guardado en favoritos');};const back=document.querySelector('#back');if(back)back.onclick=()=>{showMobile=false;render();window.scrollTo({top:0});document.querySelector('#code')?.focus();};}
function render(){updateNav();app.innerHTML=tab==='consulta'?`<div class="workspace ${showMobile?'show-result':''}">${renderSearch()}${renderResult()}</div>`:tab==='favoritos'?renderCollection():renderDocuments();app.setAttribute('aria-busy','false');bind();}
function updateOptions(){let e;try{e=resolveEvent(dataset.events,parseQuery(document.querySelector('#code').value))?.event;}catch{}document.querySelector('#sub-options').innerHTML=(e?.steps||[]).filter(s=>s.number!=null).map(s=>`<option value="${s.number}">Subíndice ${s.number}</option>`).join('');}
function updateSuggestions(){const value=document.querySelector('#code').value.trim();document.querySelector('#search-error').textContent='';const list=document.querySelector('#suggestions');const candidates=value&&!/[/\-.:]/.test(value)?dataset.events.filter(e=>e.code.startsWith(value)||String(Number(e.code)).startsWith(value)||e.title.toLowerCase().includes(value.toLowerCase())).slice(0,5):[];list.innerHTML=candidates.map(e=>`<button type="button" data-choice="${e.code}"><strong>${e.code}</strong>${escape(e.title)}</button>`).join('');list.classList.toggle('visible',candidates.length>0);list.querySelectorAll('button').forEach(b=>b.onclick=()=>{document.querySelector('#code').value=b.dataset.choice;document.querySelector('#sub').value='';list.classList.remove('visible');updateOptions();document.querySelector('#sub').focus();});updateOptions();}
function lookup(code,sub=''){try{const q=parseQuery(code,sub),found=resolveEvent(dataset.events,q);if(!found)throw new Error(`El código ${q.code} no está incluido en la base cargada. Consulta el documento de diagnóstico.`);currentQuery=q;result=found;tab='consulta';showMobile=true;history=[q,...history.filter(x=>keyOf(x)!==keyOf(q))].slice(0,8);persist();render();window.scrollTo({top:0});location.hash=keyOf(q);}catch(e){const el=document.querySelector('#search-error');if(el)el.textContent=e.message;else toast(e.message);}}
document.querySelector('.brand').onclick=e=>{e.preventDefault();tab='consulta';showMobile=false;render();window.scrollTo({top:0});};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;});document.querySelector('#install').onclick=async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;}else document.querySelector('#install-dialog').showModal();};document.querySelectorAll('.close-dialog,.close-install').forEach(b=>b.onclick=()=>document.querySelector('#install-dialog').close());
async function start(){try{const response=await fetch('data.json');if(!response.ok)throw new Error();dataset=await response.json();const hash=decodeURIComponent(location.hash.slice(1));currentQuery={code:'002',sub:null};result=resolveEvent(dataset.events,currentQuery);render();if(hash)lookup(hash);
 if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'consultar_falla_930e4',title:'Consultar falla 930E-4',description:'Abre el resultado del código y subíndice en la app y lo registra en el historial local.',inputSchema:{type:'object',properties:{codigo:{type:'string'},subcodigo:{type:'string'}},required:['codigo'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const q=parseQuery(input.codigo,input.subcodigo);const found=resolveEvent(dataset.events,q);if(!found)throw new Error('Código no documentado');lookup(input.codigo,input.subcodigo);return {codigo:q.code,subcodigo:q.sub,titulo:found.event.title,subindiceDisponible:!q.sub||found.event.steps.some(s=>s.number===Number(q.sub))};}});}catch{}}
 if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
 }catch{app.innerHTML=`<div class="empty"><h2>No se pudo cargar la base</h2><p>Revisa la conexión y vuelve a intentarlo.</p><button class="primary" id="retry">Reintentar</button></div>`;app.setAttribute('aria-busy','false');document.querySelector('#retry').onclick=start;}}
start();
